# The Docker image that will be used to build your app
image: documentation:stable
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  before_script:
    - uv pip install -U sphinx myst-parser furo
  script:
    - sphinx-build -b html docs/source/ public/
