stages:
  - build

pages:
  stage: deploy
  image: python:3.12-slim
  before_script:
    - uv pip install -U sphinx myst-parser furo
  script:
    - sphinx-build -b html docs/source/ public/
  artifacts:
    paths:
      - public