stages:
  - build

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

.setup: &create_venv
    - python --version ; pip --version  # For debugging
    - python -m venv venv
    - source venv/bin/activate
    - pip install -U uv

pages:
  stage: build
  image: python:3.12-slim
  before_script:
    - *create_venv
    - uv pip install -U sphinx myst-parser furo jupyter
  script:
    - jupyter nbconvert --to markdown ./docs/source/tutoBW_EV.ipynb
    - sphinx-build -b html docs/source/ public/
  artifacts:
    paths:
      - public